### ISSUE TITLE
GPIO base address RPI2

### ISSUE THREAD

**Issue by Wolas159** [mholling/rpirtscts#4]
GPIO base address for Raspberry Pi 2 should be 0x3F200000 instead of 0x20200000. I wasted a day to solve this problem so I hope that this post will help to some noob like me :) .

**Comment by pylover** [comment]
Interesting, but how it working till now ?

**Comment by Wolas159** [comment]
At the begining the original code was stucking in rpi_version() so I modified rpi_gpio_header_type() that it don't call  rpi_version() and always return GPIO_header_40. After that program executed without any problem but rts/cts still didn't work (I checked it by RXTX JAVA library). The key was to change  #define GPIO_BASE (0x20200000) to GPIO_BASE (0x3F200000) which finally resulted in activation RTS/CTS lines properly.

**Comment by deater** [comment]
I can confirm on Pi3 that the code as-is doesn't work unless you use the proper GPIO_BASE (as well as fixing the string matching to look for 2709).  Wasted a few hours tracking this issue down .

**Comment by bremenpl** [comment]
What is the right gpio base?

**Comment by bremenpl** [comment]
Is there way to check the RTS/CTS lines working without physically checking the pin toggle?

**Comment by deater** [comment]
I'm not sure if this is what you mean, but you can in theory read the UART_CR and UART_FR registers to get the current status of the RTS/CTS lines from software.  I have a program called dump_serial_regs
here https://github.com/deater/uarch-configure/tree/master/rasp-pi-serial which decodes those registers.

**Comment by bremenpl** [comment]
Thats what I meant, thank you.

**Comment by mholling** [comment]
thanks, fixed in 1.3
