### ISSUE TITLE
Pi3 On Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by chandong83** [mholling/rpirtscts#5]
I have Pi3 On Ubuntu Mate 16.04

my issue is "can't parse /proc/cmdline"

see below. (this is my "/proc/cmdline"
8250.nr_uarts=1 dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1366 bcm2708_fb.fbheight=768 bcm2709.boardrev=0xa02082 bcm2709.serial=0xb814368e smsc95xx.macaddr=B8:27:EB:14:36:8E bcm2708_fb.fbdepth=32 bcm2708_fb.fbswap=1 bcm2709.uart_clock=48000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait quiet splash

you can see about this issue.

my boardrev bcm2709.

Thank you

 while (fscanf(fp, "%255s", string) == 1)
                        if (sscanf(string, "bcm2708.boardrev=%i", &result))
                                break;
                        else if(sscanf(string,"bcm2709.boardrev=%i", &result))
                                break;
                fclose(fp);

**Comment by bhusang** [comment]
Pull req #3 or #7 fix this issue.

**Comment by mholling** [comment]
thanks, fixed in 1.3
